### ISSUE TITLE
mixer and composer faders do not affect plugin

### ISSUE THREAD

**Issue by danboid** [ccherrett/oom#102]
Adjusting the volume slider either from within the tracks header in the composer or from within the mixer does not effect the volume output when you have Noisemaker VST attached.

If these sliders are to remain null then they shouldn't be displayed for MIDI plugin tracks.

**Comment by ccherrett** [comment]
looking to solve this by integrating input tracks with midi and audio tracks. More to come on this.

**Comment by danboid** [comment]
Seems to be fixed now - thanks!
