### ISSUE TITLE
LinuxSampler won't start

### ISSUE THREAD

**Issue by metal3d** [ccherrett/oom#118]
I compiled last git version. I didn't compile LinuxSample myself (I need it with others tools, I don't want to break it)

Fedora 17 64bits

This is the output:

[patachou@patrice-laptop build]$ LANG=en oomidi

(process:30123): Gtk-WARNING **: Locale not supported by C library.
    Using the fallback 'C' locale.
Denormal protection enabled.
lscp_client_create: cmd: connect: Connection refused
LSThread::run: FATAL: LinuxSampler startup FAILED
Locale detected: Keyboard: fr_FR, System: en_US
no translation matching system locale <oom_en_US>/</usr/share/oom-2012.1.beta1/locale>
Looking up LADSPA plugins...
Looking up LV2 plugins...
Looking up VST plugins...
Trying RTC timer...
fatal error: open /dev/rtc failed: Permission denied
hint: check if 'rtc' kernel module is loaded, or used by something else
Trying ALSA timer...
AlsaTimer::initTimer(): best available ALSA timer: system timer
got timer = 17
starting with default template
WARNING: Cannot lock memory:: Cannot allocate memory
JACK: buffersize changed 512
JACK ERROR: JackPosixSemaphore::TimedWait err = Interrupted system call
JACK ERROR: JackPosixSemaphore::TimedWait err = Interrupted system call
JACK ERROR: JackPosixSemaphore::TimedWait err = Interrupted system call
Starting midiMonitor
WARNING: Cannot lock memory:: Cannot allocate memory
JACK ERROR: JackPosixSemaphore::TimedWait err = Interrupted system call
WARNING: Cannot lock memory:: Cannot allocate memory
JACK ERROR: JackPosixSemaphore::TimedWait err = Interrupted system call
WARNING: Cannot lock memory:: Cannot allocate memory
OOMidi Command Server Listening on port: 8415

Note that I tried to compile LinuxSample my self one month ago on a Fedora 16, I has the same error. 

Best regards

**Comment by metal3d** [comment]
linuxsampler.x86_64 0:1.0.0-6.svn2346.1.fc17.ccrma used

**Comment by metal3d** [comment]
Sorry... in fact It gives another error:

[patachou@patrice-laptop build]$ ldd /usr/bin/oomidi 
    linux-vdso.so.1 =>  (0x00007fff6edff000)
    libsndfile.so.1 => /lib64/libsndfile.so.1 (0x00007f924c538000)
    libsamplerate.so.0 => /lib64/libsamplerate.so.0 (0x00007f924c1cc000)
    libuuid.so.1 => /lib64/libuuid.so.1 (0x00007f924bfc6000)
    libdl.so.2 => /lib64/libdl.so.2 (0x00007f924bdc2000)
    libgtk-x11-2.0.so.0 => /lib64/libgtk-x11-2.0.so.0 (0x00007f924b74c000)
    libgdk-x11-2.0.so.0 => /lib64/libgdk-x11-2.0.so.0 (0x00007f924b48c000)
    libatk-1.0.so.0 => /lib64/libatk-1.0.so.0 (0x00007f924b26a000)
    libgio-2.0.so.0 => /lib64/libgio-2.0.so.0 (0x00007f924af1d000)
    libpangoft2-1.0.so.0 => /lib64/libpangoft2-1.0.so.0 (0x00007f924acf0000)
    libpangocairo-1.0.so.0 => /lib64/libpangocairo-1.0.so.0 (0x00007f924aae3000)
    libgdk_pixbuf-2.0.so.0 => /lib64/libgdk_pixbuf-2.0.so.0 (0x00007f924a8c1000)
    libcairo.so.2 => /lib64/libcairo.so.2 (0x00007f924a615000)
    libpango-1.0.so.0 => /lib64/libpango-1.0.so.0 (0x00007f924a3ca000)
    libfreetype.so.6 => /lib64/libfreetype.so.6 (0x00007f924a129000)
    libfontconfig.so.1 => /lib64/libfontconfig.so.1 (0x00007f9249ef3000)
    libgobject-2.0.so.0 => /lib64/libgobject-2.0.so.0 (0x00007f9249ca6000)
    libgmodule-2.0.so.0 => /lib64/libgmodule-2.0.so.0 (0x00007f9249aa2000)
    libgthread-2.0.so.0 => /lib64/libgthread-2.0.so.0 (0x00007f924989f000)
    librt.so.1 => /lib64/librt.so.1 (0x00007f9249697000)
    libglib-2.0.so.0 => /lib64/libglib-2.0.so.0 (0x00007f9249378000)
    liblscp.so.6 => /lib64/liblscp.so.6 (0x00007f9249165000)
    libasound.so.2 => /lib64/libasound.so.2 (0x00007f9248e86000)
    libjack.so.0 => /lib64/libjack.so.0 (0x00007f9248c32000)
    libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f9248a15000)
    libQtDesigner.so.4 => /lib64/libQtDesigner.so.4 (0x00007f92482c7000)
    libQtSvg.so.4 => /lib64/libQtSvg.so.4 (0x00007f9248071000)
    libQtWebKit.so.4 => /lib64/libQtWebKit.so.4 (0x00007f924624c000)
    libQtXmlPatterns.so.4 => /lib64/libQtXmlPatterns.so.4 (0x00007f9245c07000)
    libQtGui.so.4 => /lib64/libQtGui.so.4 (0x00007f9244f66000)
    libQtXml.so.4 => /lib64/libQtXml.so.4 (0x00007f9244d24000)
    libQtNetwork.so.4 => /lib64/libQtNetwork.so.4 (0x00007f92449ef000)
    libQtCore.so.4 => /lib64/libQtCore.so.4 (0x00007f9244522000)
    libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f924421e000)
    libm.so.6 => /lib64/libm.so.6 (0x00007f9243f23000)
    libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f9243d0e000)
    libc.so.6 => /lib64/libc.so.6 (0x00007f9243956000)
    libgsm.so.1 => /lib64/libgsm.so.1 (0x00007f924374b000)
    libFLAC.so.8 => /lib64/libFLAC.so.8 (0x00007f9243511000)
    libvorbisenc.so.2 => /lib64/libvorbisenc.so.2 (0x00007f9243041000)
    libvorbis.so.0 => /lib64/libvorbis.so.0 (0x00007f9242e14000)
    libogg.so.0 => /lib64/libogg.so.0 (0x00007f9242c0d000)
    /lib64/ld-linux-x86-64.so.2 (0x00007f924c7c2000)
    libX11.so.6 => /lib64/libX11.so.6 (0x00007f92428d2000)
    libXfixes.so.3 => /lib64/libXfixes.so.3 (0x00007f92426cc000)
    libXext.so.6 => /lib64/libXext.so.6 (0x00007f92424ba000)
    libXrender.so.1 => /lib64/libXrender.so.1 (0x00007f92422af000)
    libXinerama.so.1 => /lib64/libXinerama.so.1 (0x00007f92420ac000)
    libXi.so.6 => /lib64/libXi.so.6 (0x00007f9241e9d000)
    libXrandr.so.2 => /lib64/libXrandr.so.2 (0x00007f9241c94000)
    libXcursor.so.1 => /lib64/libXcursor.so.1 (0x00007f9241a89000)
    libXcomposite.so.1 => /lib64/libXcomposite.so.1 (0x00007f9241886000)
    libXdamage.so.1 => /lib64/libXdamage.so.1 (0x00007f9241682000)
    libffi.so.5 => /lib64/libffi.so.5 (0x00007f924147a000)
    libz.so.1 => /lib64/libz.so.1 (0x00007f9241263000)
    libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f9241041000)
    libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f9240e27000)
    libpng15.so.15 => /lib64/libpng15.so.15 (0x00007f9240bfc000)
    libpixman-1.so.0 => /lib64/libpixman-1.so.0 (0x00007f9240976000)
    libexpat.so.1 => /lib64/libexpat.so.1 (0x00007f924074c000)
    libcelt0.so.2 => /lib64/libcelt0.so.2 (0x00007f9240534000)
    libQtScript.so.4 => /lib64/libQtScript.so.4 (0x00007f9240093000)
    libsqlite3.so.0 => /usr/lib64/libsqlite3.so.0 (0x00007f923fded000)
    libgstapp-0.10.so.0 => /usr/lib64/libgstapp-0.10.so.0 (0x00007f923fbe1000)
    libgstinterfaces-0.10.so.0 => /usr/lib64/libgstinterfaces-0.10.so.0 (0x00007f923f9ce000)
    libgstpbutils-0.10.so.0 => /usr/lib64/libgstpbutils-0.10.so.0 (0x00007f923f7ab000)
    libgstvideo-0.10.so.0 => /usr/lib64/libgstvideo-0.10.so.0 (0x00007f923f58f000)
    libgstbase-0.10.so.0 => /usr/lib64/libgstbase-0.10.so.0 (0x00007f923f33a000)
    libgstreamer-0.10.so.0 => /usr/lib64/libgstreamer-0.10.so.0 (0x00007f923f054000)
    libxml2.so.2 => /usr/lib64/libxml2.so.2 (0x00007f923ecfc000)
    libQtLocation.so.1 => /usr/lib64/libQtLocation.so.1 (0x00007f923e9c3000)
    libQtSensors.so.1 => /usr/lib64/libQtSensors.so.1 (0x00007f923e7a1000)
    libSM.so.6 => /lib64/libSM.so.6 (0x00007f923e598000)
    libICE.so.6 => /lib64/libICE.so.6 (0x00007f923e37c000)
    libssl.so.10 => /lib64/libssl.so.10 (0x00007f923e120000)
    libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00007f923dd86000)
    libxcb.so.1 => /lib64/libxcb.so.1 (0x00007f923db67000)
    liborc-0.4.so.0 => /usr/lib64/liborc-0.4.so.0 (0x00007f923d8eb000)
    libQtSql.so.4 => /usr/lib64/libQtSql.so.4 (0x00007f923d6ad000)
    libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007f923d468000)
    libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007f923d183000)
    libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007f923cf7f000)
    libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007f923cd53000)
    libXau.so.6 => /lib64/libXau.so.6 (0x00007f923cb4f000)
    libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007f923c943000)
    libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007f923c740000)
[patachou@patrice-laptop build]$ oomidi 
Denormal protection enabled.
lscp_client_create: cmd: connect: Connexion refusée
Locale detected: Keyboard: fr_FR, System: fr_FR
Looking up LADSPA plugins...
Looking up LV2 plugins...
Looking up VST plugins...
Trying RTC timer...
fatal error: open /dev/rtc failed: Permission non accordée
hint: check if 'rtc' kernel module is loaded, or used by something else
Trying ALSA timer...
AlsaTimer::initTimer(): best available ALSA timer: system timer
got timer = 24
starting with default template
LSThread::pingLinuxsampler: Description: LinuxSampler - modular, streaming capable sampler, Version: 1.0.0.svn18, Protocol Version: 1.5

WARNING: Cannot lock memory:: Ne peut allouer de la mémoire
JACK: buffersize changed 512
JACK ERROR: JackPosixSemaphore::TimedWait err = Appel système interrompu
JACK ERROR: JackPosixSemaphore::TimedWait err = Appel système interrompu
Starting midiMonitor
JACK ERROR: JackPosixSemaphore::TimedWait err = Appel système interrompu
WARNING: Cannot lock memory:: Ne peut allouer de la mémoire
JACK ERROR: JackPosixSemaphore::TimedWait err = Appel système interrompu
WARNING: Cannot lock memory:: Ne peut allouer de la mémoire
WARNING: Cannot lock memory:: Ne peut allouer de la mémoire
OOMidi Command Server Listening on port: 8415
LinuxSampler::ERROR: Could not open instrument editor plugins directory ('/usr/lib64/linuxsampler/plugins'): No such file or directory
LinuxSampler::ERROR: Thread: WARNING, can't mlockall() memory!
LSClient::startClient: hostname: localhost, port: 8888
Initialized LSCP client connection
LinuxSampler::ERROR: Cannot lock down 42433306 byte memory area (Ne peut allouer de la mémoire)
TrackManager::createMonitorInputTracks: conf_name: LinuxSampler:1stviolins-audio
TrackManager::createMonitorInputTracks: cname: LinuxSampler:1stviolins-audio
TrackManager::createMonitorInputTracks: 
    id: 1345115407490900571,    type: 3, 
    srcTrack: 0x0,
     dstTrack: 0x3553560,
     srcTid: 0, 
    dstTid: 1345115406650961111,
    midiPort: 0, 
    midiDevice: 0x0, 
    srcPort: 0xc, 
    dstPort: 0x0, 
    srcChan: -1, 
    dstChan: 0
TrackManager::createMonitorInputTracks: conf_name: LinuxSampler:1stviolins-audio
TrackManager::createMonitorInputTracks: cname: LinuxSampler:1stviolins-audio
TrackManager::createMonitorInputTracks: 
    id: 1345115406284356593,    type: 3, 
    srcTrack: 0x0,
     dstTrack: 0x3553560,
     srcTid: 0, 
    dstTid: 1345115406650961111,
    midiPort: 0, 
    midiDevice: 0x0, 
    srcPort: 0xc, 
    dstPort: 0x0, 
    srcChan: -1, 
    dstChan: 1
LinuxSampler::ERROR: Thread: WARNING, can't mlockall() memory!

**Comment by metal3d** [comment]
Note that I can hear metronom, Linuxsampler appears in the audio node view, Jack connection are ok from linuxsampler to audio out...

Probmel is that I don't have sound that is played excepting metronom...

**Comment by ccherrett** [comment]
Patrice Ferlet wrote:

> Note that I can hear metronom, Linuxsampler appears in the audio node 
> view, Jack connection are ok from linuxsampler to audio out...
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/ccherrett/oom/issues/118#issuecomment-7782791.
> 
> How did you install oomidi and how are you running it? From oostudio or 
> oomidi?

## 

Christopher Cherrett
ccherrett@openoctave.org
http://www.openoctave.org

**Comment by metal3d** [comment]
I use oomidi. I made a mistake: Linuxsampler is working and I see ports in JAck (I'm using qjackcontrol). The only problem is that I don't hear some sound excepting metronom.

My jack configuration is ok (ardour, lmms, etc... works) I didn't tried Qsampler but I can in a few minutes.

This problem is the same as with my Fedora 16 (one week ago) when I compiled libs myself (libv2, lscp etc...) So the problem should be something else.

(or maybe, I don't use oomidi as I should...)

**Comment by metal3d** [comment]
Ok, so LinuxSample works with a simple SFZ file (Qsampler test). But when I try the "templates" sfz files given with oomidi, an error appears telling that waves file are not found...

So, libgig, linuxsample, etc... are ok. I try to append some LS banks, using "performer" view and pressing some keys: no sound. No error on term (excepting messages I paster here). This is strange, or maybe something is missing.

**Comment by metal3d** [comment]
When I create track (midi, LS instrument):

LinuxSampler::ERROR: Thread: WARNING, can't mlockall() memory!
LSClient::startClient: hostname: localhost, port: 8888
Initialized LSCP client connection
LinuxSampler::ERROR: Cannot lock down 42433306 byte memory area (Ne peut allouer de la mémoire)
TrackManager::createMonitorInputTracks: conf_name: LinuxSampler:1stviolins-audio
TrackManager::createMonitorInputTracks: cname: LinuxSampler:1stviolins-audio
TrackManager::createMonitorInputTracks: 
    id: 1345146394490900571,    type: 3, 
    srcTrack: 0x0,
     dstTrack: 0x3910a20,
     srcTid: 0, 
    dstTid: 1345146393650961111,
    midiPort: 0, 
    midiDevice: 0x0, 
    srcPort: 0xc, 
    dstPort: 0x0, 
    srcChan: -1, 
    dstChan: 0

**Comment by ccherrett** [comment]
Did you install the instruments, sonitina, maestro grand?

You can find them here:

http://sourceforge.net/projects/openoctave/files/libraries/

Extract them to ~/.sounds/

That will give openoctave some samples to play with.

Patrice Ferlet wrote:

> When I create track (midi, LS instrument):
> 
> LinuxSampler::ERROR: Thread: WARNING, can't mlockall() memory!
> LSClient::startClient: hostname: localhost, port: 8888
> Initialized LSCP client connection
> LinuxSampler::ERROR: Cannot lock down 42433306 byte memory area (Ne 
> peut allouer de la mémoire)
> TrackManager::createMonitorInputTracks: conf_name: 
> LinuxSampler:1stviolins-audio
> TrackManager::createMonitorInputTracks: cname: 
> LinuxSampler:1stviolins-audio
> TrackManager::createMonitorInputTracks:
> id: 1345146394490900571, type: 3,
> srcTrack: 0x0,
> dstTrack: 0x3910a20,
> srcTid: 0,
> dstTid: 1345146393650961111,
> midiPort: 0,
> midiDevice: 0x0,
> srcPort: 0xc,
> dstPort: 0x0,
> srcChan: -1,
> dstChan: 0
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/ccherrett/oom/issues/118#issuecomment-7797154.

## 

Christopher Cherrett
ccherrett@openoctave.org
http://www.openoctave.org

**Comment by metal3d** [comment]
My god... I didn't know we should install some gig files... and now it works... 
Thanks a lot, and sorry for the time you spent to aswer me...

Now, I only have to learn how to use it :)

Thanks again

**Comment by ccherrett** [comment]
Patrice Ferlet wrote:

> My god... I didn't know we should install some gig files... and now it 
> works...
> Thanks a lot, and sorry for the time you spent to aswer me...
> 
> Now, I only have to learn how to use it :)
> 
> Thanks again
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/ccherrett/oom/issues/118#issuecomment-7801802.
> 
> you can always ask us for help in #openoctave on freenode irc

## 

Christopher Cherrett
ccherrett@openoctave.org
http://www.openoctave.org

**Comment by metal3d** [comment]
Ok, I'm daily on #fedora-fr channel, I will come soon. It's late at night in France ;) 
My nickname is Metal3d.

See ya, thanks (I close this issue)
