### ISSUE TITLE
Event List Window: Resize not retained across restarts.

### ISSUE THREAD

**Issue by alekz49** [ccherrett/oom#21]
Same resize problem as other windows, not retained across restarts. Have asked Remon to set default size that at least shows all info.

**Comment by linuxras** [comment]
This is slated for oom3 development cycle.

**Comment by rsijrier** [comment]
fixed

**Comment by linuxras** [comment]
Nice Job Remon

**Comment by alekz49** [comment]
Testing and working. Thanks Remon.
