### ISSUE TITLE
Event List Editor: CC event should be inserted at current time position value for highlighted event

### ISSUE THREAD

**Issue by alekz49** [ccherrett/oom#25]
When inserting a event in the list editor the bar/beat/tick position is always 0001.01.000. (0 ticks) This doesn't make sense if we're operating at bar 225. Inserting an event should, by default, be at the time position of the existing highlighted event in the list. So if an existing event is at time position 0008.03.256, we then press the button (shortcut is implemented already) for "New CTRL event), and the time position for the new event is displayed as current highlighted position 0008.03.256, not 0001.01.000

**Comment by linuxras** [comment]
This is slated for oom3 development cycle.

**Comment by alekz49** [comment]
This is fixed and works. Thanks Remon.
