### ISSUE TITLE
Arranger window: Selected track disappears from view.

### ISSUE THREAD

**Issue by alekz49** [ccherrett/oom#29]
Related to the arranger window scrolling issue, when the active track selected reaches the bottom of the tracks in the window, it disappears out of sight.
The selected/active track should always be visible in the window, and scroll the canvas if we have more tracks than can appear in 1 window.

**Comment by alekz49** [comment]
Remon and I have discussed this. He will have a look if he has time in the near future.

**Comment by rsijrier** [comment]
fixed in git

**Comment by alekz49** [comment]
Tested and works. As discussed, when the highlighted track is at the bottom of the window, the next track is taken to the middle of the window.
