### ISSUE TITLE
REMON: active note navigation in PR combined with PB.

### ISSUE THREAD

**Issue by alekz49** [ccherrett/oom#39]
This is added for discussion at a later date, and is not currently tied to any dev cycle label, hence it's wishlist tag.

When we navigate from note to note in the PR, and keep going right to an active note that's not in view, the canvas doesn't adjust to always keep the active note in view. This is because we have implemented the PB cursor always being in view, and the canvas only responds to the PB behaviour as the first priority.

I propose a change to this behaviour, to have the PB "follow" the active note, at the left edge of the active note by default.

This serves 2 purposes. 

1.) We retain the navigation behaviour of the PB always being in view, in the main canvas.

2.) We are always where we are working. If we choose a note to be active, it's assumed we want to do some thing to that note, and it makes no sense to have an active note that is not in view all the time, at least for the majority of use cases.

discussion on this would be welcome.

**Comment by alekz49** [comment]
Not part of the current development cycles.

**Comment by alekz49** [comment]
Moved to oom2 in the dev cycle

**Comment by alekz49** [comment]
Additional discussion suggest that the active note is always in view, and we add a shortcut to move the PB cursor to the active note, so the PB is in view as well, and at the working position.

**Comment by rsijrier** [comment]
works now in git

**Comment by alekz49** [comment]
Tested and works. Thanks Remon.
