### ISSUE TITLE
PRIORITY: Ctrl + S doesn't work in the PR

### ISSUE THREAD

**Issue by alekz49** [ccherrett/oom#42]
The Ctrl + S (save) function doesn't work in the PR. This is an important one as we don't want to lose all our work. (obviously)

**Comment by alekz49** [comment]
It would be worth checking other "standard" shortcuts, as well as the Ctrl + S problem.

**Comment by rsijrier** [comment]
fixed that in git, please test

**Comment by alekz49** [comment]
Tested, Works, thanks.
