### ISSUE TITLE
Port button in midi track problem still not solved.

### ISSUE THREAD

**Issue by alekz49** [ccherrett/oom#47]
After a quick discussion with Andrew, and his subsequent push to fix the port button error, i've failed to get it working. I've added this ticket as a result. 

Tested with a new project, and clean build from GIT. 26.01.2011 19.30 GMT

**Comment by ccherrett** [comment]
Old projects might have old configs. Is this happening with new projects.

**Comment by alekz49** [comment]
Works fine now, my bad.
