### ISSUE TITLE
TESTING:Controller lane events change width or diasappear when the PB cursor passes over them

### ISSUE THREAD

**Issue by alekz49** [ccherrett/oom#5]
When the PB passes over events in the controller lanes, the events change to narrow, or disappear. Moving the PB backwards makes events resume their previous width. (Drawing problem)

**Comment by rsijrier** [comment]
Fixed by drawing the whole controller lane, might use too much cpu, needs a real fix.

**Comment by alekz49** [comment]
So far so good in testing. A little increase in CPU, but nothing significant. The ifx has probably added about 5% CPU usage. In context this is negligible on a reasonably powered box.

**Comment by alekz49** [comment]
Working ok.
