### ISSUE TITLE
Compile error without LV2. Fix suggested.

### ISSUE THREAD

**Issue by Kaffeine** [ccherrett/oom#52]
/var/tmp/portage/media-sound/openoctave-midi-2011.3/work/oom-2011.3/oom/mixer/rack.cpp: In member function ‘void EffectRack::menuRequested(QListWidgetItem_)’:
/var/tmp/portage/media-sound/openoctave-midi-2011.3/work/oom-2011.3/oom/mixer/rack.cpp:262: error: ‘class QAction’ has no member named ‘hide’
distcc[28259] ERROR: compile (null) on localhost failed
make[2]: *_\* [oom/mixer/CMakeFiles/mixer.dir/rack.o] Error 1
make[2]: **\* Waiting for unfinished jobs....
## oom/mixer/rack.cpp:257-263:

```
#if defined(OSC_SUPPORT) || defined(LV2_SUPPORT)
    showNativeGuiAction->setEnabled(true);
#else
    printf("Disabling show Native\n");
    showNativeGuiAction->setEnabled(false);
    showNativeGuiAction->hide();
#endif
```

---

showNativeGuiAction is pointer to QAction, that have not method hide, may be instead here should be setVisible(false)?

**Comment by ccherrett** [comment]
Kaffeine wrote:

> /var/tmp/portage/media-sound/openoctave-midi-2011.3/work/oom-2011.3/oom/mixer/rack.cpp: In member function ‘void EffectRack::menuRequested(QListWidgetItem_)’:
> /var/tmp/portage/media-sound/openoctave-midi-2011.3/work/oom-2011.3/oom/mixer/rack.cpp:262: error: ‘class QAction’ has no member named ‘hide’
> distcc[28259] ERROR: compile (null) on localhost failed
> make[2]: *_\* [oom/mixer/CMakeFiles/mixer.dir/rack.o] Error 1
> make[2]: **\* Waiting for unfinished jobs....
> 
> ## oom/mixer/rack.cpp:257-263:
> 
> ```
> #if defined(OSC_SUPPORT) || defined(LV2_SUPPORT)
>   showNativeGuiAction->setEnabled(true);
> #else
>   printf("Disabling show Native\n");
>   showNativeGuiAction->setEnabled(false);
>   showNativeGuiAction->hide();
> #endif
> ```
> 
> ---
> 
> showNativeGuiAction is pointer to QAction, that have not method hide, may be instead here should be setVisible(false)?
> 
> Thank you very much for the report.

Re-pull the 2011.3 tar ball.

Let me know if the new tarball works for you. I take it you were
compiling without lv2 support?

## 

Christopher Cherrett
ccherrett@openoctave.org
http://www.openoctave.org

**Comment by Kaffeine** [comment]
Thank you for fast answer and new tar ball, now all works fine.
