### ISSUE TITLE
Fix application bug

### ISSUE THREAD

**Issue by alekz49** [ccherrett/oom#55]
As requested, this bug is added to the issue list.

No success pinning down what actions or actions creates this notification so far.

Denormal protection enabled.
no locale <oom_en_US>/</usr/local/share/oom-2011.3.2/locale>
Found 259 LV2 Plugins
Master plugin list contains 578 plugins
Trying RTC timer...
RtcTimer::setTimerFreq(): cannot set tick on /dev/rtc: Permission denied
  precise timer not available
Trying ALSA timer...
AlsaTimer::initTimer(): best available ALSA timer: system timer
got timer = 245
starting with default template
OOMidi::clearSong() TopLevel.size(0) 
OOMidi::loadProjectFile1 Before OOMidi::read()
OOMidi::loadProjectFile1 After OOMidi::read()
JACK: buffersize changed 512
Starting midiMonitor
OOMidi Command Server Listening on port: 8415
Stoping midiMonitor
OOMidi::clearSong() TopLevel.size(1) 
Setting project path to /home/alex/audio-projects
OOMidi::loadProjectFile1 Before OOMidi::read()
OOMidi::loadProjectFile1 After OOMidi::read()
JACK: buffersize changed 512
Starting midiMonitor
Application asked to unregister timer 0x37000008 which is not registered in this  
 thread. Fix application.
Application asked to unregister timer 0x45000019 which is not registered in this  
 thread. Fix application.
Application asked to unregister timer 0x7b000013 which is not registered in this  
 thread. Fix application.
Application asked to unregister timer 0x6500000e which is not registered in this  
 thread. Fix application.
Application asked to unregister timer 0x2d000023 which is not registered in this  
 thread. Fix application.

**Comment by ccherrett** [comment]
cannot reproduce
