### ISSUE TITLE
Can only hear the metronome

### ISSUE THREAD

**Issue by normism** [ccherrett/oom#57]
Howdy, 

I've got Sonatina installed, but still get no sound from instruments using the orchestral template. 

I can hear the metronome when trying to play, but i don't get any sound from instruments - either in audition or from trying to play notes laid out. I can see the volume meter on the instrument(s) has activity, but nothing on master ever changes. 

Any insight or advice here?  It seems like I'm just missing something simple and fundamental, but troubleshooting tips don't seem to offer any insight to what might be happening.

**Comment by ccherrett** [comment]
ls ~/.sounds/sonatina/Sonatina\ Symphonic\ Orchestra/

is this where things are installed for sonitina?

**Comment by normism** [comment]
Documentation said /usr/share/sounds/ for it  tried .sounds as suggested. Sill only hear a metronome. The instrument shows volume activity during play, but 'master' track doesn't.

**Comment by ccherrett** [comment]
When you say "volume activity" do you mean on the midi track?

Can you test by starting with oostudio?

**Comment by normism** [comment]
Yes... volume meter on the midi track shows activity during playback. 

Effect is the same whether starting oostudio or oomidi on the command line.

**Comment by ccherrett** [comment]
That points to samples not loading in linuxsampler. linuxsampler 1.0 does not support sfz and you need the latest svn copy.

https://github.com/ccherrett/oom/wiki/Installing-OOM

look under the heading Template Set

you will need libgig, liblscp and linuxsampler

**Comment by ccherrett** [comment]
bedtime for me will check up on you when I get up, please follow up and I will help you out

**Comment by normism** [comment]
Installed packages: 
linuxsampler-1.0.0-5.fc16.ccrma.x86_64
liblscp-0.5.6-0.fc15.x86_64
libgig-3.3.0-2.fc16.ccrma.x86_64

So will get onto building new linuxsampler in my morning as well.

**Comment by ccherrett** [comment]
I think that version is too old. I am going to version check linuxsampler and warn users in a coming release.

Sorry for your hassles.

**Comment by normism** [comment]
Ok... SVN checkout of libgig and linuxsampler and I can hear instruments now. Thanks :)

and on https://github.com/ccherrett/oom/wiki/Installing-OOM
1 Open a terminal, and type:

 cd ~/Downloads

2 Install the SSO with the following command:

 sudo tar xjf sonatina1.tar.bz2 -C /usr/share/sounds/

3 You should now have the Sonatina library installed on your system, in /usr/share/sounds, and you can check this with the command:

 ls -lah /usr/share/sounds/

Says to put sonatina in a different place than you said in your first comment. 

Will be busy tonight playing :)

**Comment by ccherrett** [comment]
very cool! Thanks for sticking around to solve it. It looks like the next version of oomidi will package LS with everything turned on

**Comment by normism** [comment]
Great - thanks for the help. 

Robust version / capability testing, good error message when things are wrong or in the wrong place can really help. Paranoid programming - it all works on your workstation because you code for things to be where you put them, but how does the software deal when things are in a different place?  How much can be 'sniffed', how much is portable (different distro's that might want to include the package might want to put it in a different location, so hard paths are bad). 

I want to say that I'm really really excited to start working with this, I've lightly been looking for an app like this for 20 years (been on linux for 15, and just hasn't been anything like this here until now). 

Thanks for the great vision :)

**Comment by ccherrett** [comment]
you can always find us in #openoctave on irc.freenode.org
