### ISSUE TITLE
CTRL+A selects but cannot use octave shifting with it

### ISSUE THREAD

**Issue by ccherrett** [ccherrett/oom#60]
CTRL+A selects but cannot use octave shifting with it. After all notes are selected using SHIFT+UP does nothing.

**Comment by linuxras** [comment]
I have managed to recreate this locally.

Its the result of a focus issue, if you click in the canvas before you CTRL+A it works fine.
I'm going to add the shortcut to the menu system and up a level from the canvas so that it does not matter where the focus is.

**Comment by linuxras** [comment]
Added actions to the Functions menu for all the supported actions on the canvas with their hotkeys defined

This issue is closed.
