### ISSUE TITLE
play events doesn't work (with VST synths)

### ISSUE THREAD

**Issue by danboid** [ccherrett/oom#77]
I don't hear anything when inserting notes into the performer on a MIDI track loaded with a VSTi synth such as Loomer Aspect or Noisemaker when then 'Play Events' (the speaker icon in the performer window) icon is active.

**Comment by ccherrett** [comment]
inserting notes with what? the draw tool and mouse, your qwerty, a midi keyboard?

**Comment by ccherrett** [comment]
you need to report if it is happening with lv2 synths as well. It is a very valid test that I need to have done on any vst synth reports.

**Comment by danboid** [comment]
Yes, I don't hear anything when inserting notes with the draw tool and mouse - presume this is how I am working in future if I leave this off as I will be sure to mention if I'm using any special (MIDI) hardware or extra apps.

'Play Events' doesn't work for both the LV2 and VST versions of Noisemaker nor Aspect (VST) when inserting notes with the draw tool and mouse.

**Comment by ccherrett** [comment]
Ah I see your point. It was left this way on purpose....... but not that is is not a valid case. We will put it in

**Comment by ccherrett** [comment]
I did test the vst synths on a non-rt kernel. So I am able to debug what is happening for you now.

**Comment by linuxras** [comment]
DONE

Notes will now play as they are drawn with all Instrument types

Thanks very much for your request.

This issue is closed.
