### ISSUE TITLE
instruments no longer remember their patch sequence lists

### ISSUE THREAD

**Issue by ccherrett** [ccherrett/oom#80]
instruments no longer remember their patch sequence lists, I might be remembering this wrong but did not the sequence list get stored with the instrument?

Or did it get stored with the track and now that we no longer use a template our sequence list does not follow us?

Can it be part of the idf so it follows the instrument/synth?

Since synth is not an idf we may need to make other provision for it.

**Comment by linuxras** [comment]
No the patch sequence is stored in the OOM  MidiPort not the instrument as the instrument can be used on a different port on which you want a different sequence of patches.

So if you make a sequence for any instrument type it should save and be restored with the Midi Port state, no matter if Synth or idf.

I'm closing this one as I see no bug.
