### ISSUE TITLE
(Noisemaker) LV2 plugin JACK routing weirdness

### ISSUE THREAD

**Issue by danboid** [ccherrett/oom#85]
If I create a track using the latest git LV2 version of Noisemaker (under the latest git version of OOM) its JACK routing looks like this before saving the session:

system:capture_1
system:capture_2
system:playback_1
   OOMidi:Master-0
system:playback_2
   OOMidi:Master-1
alsa_pcm:Midi-Through/midi_capture_1
alsa_pcm:Midi-Through/midi_playback_1
alsa_pcm:SB-Live--5-1--SB0060-/midi_capture_1
alsa_pcm:SB-Live--5-1--SB0060-/midi_playback_1
alsa_pcm:Emu10k1-WaveTable/midi_playback_1
alsa_pcm:Emu10k1-WaveTable/midi_playback_2
alsa_pcm:Emu10k1-WaveTable/midi_playback_3
alsa_pcm:Emu10k1-WaveTable/midi_playback_4
alsa_pcm:OOMidi/midi_capture_1
alsa_pcm:OOMidi/midi_playback_1
OOMidi:Master-0
   system:playback_1
OOMidi:Master-1
   system:playback_2
OOMidi:O-nmlv2-test:Audio Input 1
OOMidi:O-nmlv2-test:Audio Input 2
OOMidi:O-nmlv2-test:Audio Output 1
   OOMidi:inmlv2-test-0
OOMidi:O-nmlv2-test:Audio Output 2
   OOMidi:inmlv2-test-1
OOMidi:inmlv2-test-0
   OOMidi:O-nmlv2-test:Audio Output 1
OOMidi:inmlv2-test-1
   OOMidi:O-nmlv2-test:Audio Output 2

After saving, closing OOM and re-opening the very same session, the JACK routing gets altered. In this case:

system:capture_1
system:capture_2
system:playback_1
   OOMidi:Master-0
system:playback_2
   OOMidi:Master-1
alsa_pcm:Midi-Through/midi_capture_1
alsa_pcm:Midi-Through/midi_playback_1
alsa_pcm:SB-Live--5-1--SB0060-/midi_capture_1  
alsa_pcm:SB-Live--5-1--SB0060-/midi_playback_1  
alsa_pcm:Emu10k1-WaveTable/midi_playback_1  
alsa_pcm:Emu10k1-WaveTable/midi_playback_2  
alsa_pcm:Emu10k1-WaveTable/midi_playback_3  
alsa_pcm:Emu10k1-WaveTable/midi_playback_4  
alsa_pcm:OOMidi/midi_capture_1  
alsa_pcm:OOMidi/midi_playback_1  
OOMidi:O-nmlv2-test:Audio Input 1  
OOMidi:O-nmlv2-test:Audio Input 2  
OOMidi:O-nmlv2-test:Audio Output 1  
   OOMidi:inmlv2-test-0  
OOMidi:O-nmlv2-test:Audio Output 2  
   OOMidi:inmlv2-test-1  
OOMidi:Master-0  
   system:playback_1  
OOMidi:Master-1  
   system:playback_2
OOMidi:inmlv2-test-0
   OOMidi:O-nmlv2-test:Audio Output 1
OOMidi:inmlv2-test-1
   OOMidi:O-nmlv2-test:Audio Output 2

That's just one example but it doesn't always happen like that. Sometimes it will connect the Master bus to the system outputs and sometimes not - that is the main issue here I think.

**Comment by ccherrett** [comment]
seems to be fixed now so closing
