### ISSUE TITLE
Add default and GUI set up of VST plugin paths

### ISSUE THREAD

**Issue by danboid** [ccherrett/oom#86]
ATM it seems the only way to have OOM find your VST plugins is to export VST_PATH.

OOM should have at least 1 default VST plugin path and you should be able to add more easily under Global Settings

**Comment by danboid** [comment]
For the default paths may I suggest:

/usr/local/lib/vst
/usr/lib/vst

for x86 and

/usr/local/lib64/vst
/usr/lib64/vst

to cover x86-64 LinuxVSTs

**Comment by falkTX** [comment]
the defaults path are currently:
/usr/local/lib64/vst,
/usr/lib64/vst,
/usr/local/lib/vst,
/usr/lib/vst

if you place your VSTs there, it will load them without using VST_PATH

A GUI for setting up extra folders will be added at a later time

**Comment by linuxras** [comment]
Issue fixed Settings->Global Setting, Added fields to enable/disable loading of plugin type and manage default plugin paths
