### ISSUE TITLE
Add file dialogue and dir history to 'Bounce to File' window

### ISSUE THREAD

**Issue by danboid** [ccherrett/oom#87]
As it stands, if you want to bounce your session to any other dir other than your home dir you need to manually type (or copy and paste from a terminal) the full path to where you want the bounce saved but it would be much more user friendly if there was a 'browse' icon to point and click to your destination.

Also, OOM should ideally remember previous bounce dirs and let you select them from a drop-down menu.

**Comment by ccherrett** [comment]
fixed, the browse button was there but it had no icon and tooltip and our styles have no borders on buttons so it was invisible :)
