### ISSUE TITLE
A few tweaks for conductor patch list management

### ISSUE THREAD

**Issue by danboid** [ccherrett/oom#91]
I have quickly become a great fan of the patch list within the conductor section of the orchestra pit but I think it would be much better if:
- Currently, selected patches get added to the bottom of the list which would be fine if that was the order of preference in the list (ie bottom to top) but that is not the case so it makes much more sense to me that new patches should get added to the top of the patch list instead of the bottom.
- Seeing as the policy is 'top patch is active' in the patches window, I suggest a new icon be added to the left of the 'Move up' icon that instantly moves the selected patch to the top of the list. Two arrows pointing up would be a logical symbol for this feature.
- You should be able to re-arrange the patches by dragging them up and down the list

If we get all that sorted we have a killer feature on our hands for sure!!

**Comment by ccherrett** [comment]
discuss this with me in irc so I can teach you how it is suppose to function.

**Comment by ccherrett** [comment]
I think all the bugs are out so I will close this.
