### ISSUE TITLE
Wrong BPM displayed initially when bringing up the tempo-editor

### ISSUE THREAD

**Issue by zth** [ccherrett/oom#94]
Bringing up the tempo-editor shows 30 bpm at "current position" (at the start of the song) when the graph shows the song being at its default 120bpm. The actual bpm is also 120, confirmed by playback. "Workaround": Drag the marker from 0, away some, and back to 0 and the correct bpm is displayed. It is only initially that the incorrect 30bpm is displayed.

**Comment by linuxras** [comment]
Fixed by calling posChanged() with the current song position causes it to properly update
